---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-test-pv-file
  namespace: csi-driver-test
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-nfs
  nfs:
    path: /tmp
    server: 172.17.0.2
