---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-test-pvc-file
  namespace: csi-driver-test
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
